#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  AgoraIQ — site-wide mobile responsive deploy
#  • Creates /opt/agoraiq-signals/web/assets/agoraiq-mobile.{css,js}
#  • Patches every *.html in /opt/agoraiq-signals/web/ to:
#     - Use optimized Google Fonts (preconnect + Syne display=block)
#     - Include the shared mobile CSS + JS
#     - Have a proper viewport meta tag
#  • Idempotent: safe to re-run.
#  • Backs up everything before touching it.
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

WEB_DIR="/opt/agoraiq-signals/web"
ASSETS_DIR="$WEB_DIR/assets"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$WEB_DIR/.mobile-patch-backup-$TIMESTAMP"

[ -d "$WEB_DIR" ] || { echo "ERROR: $WEB_DIR does not exist"; exit 1; }
mkdir -p "$ASSETS_DIR" "$BACKUP_DIR"

echo "▸ Backup dir: $BACKUP_DIR"
cp "$WEB_DIR"/*.html "$BACKUP_DIR/" 2>/dev/null || true

# ─────────────────────────────────────────────────────────────────
# 1. Shared mobile CSS
# ─────────────────────────────────────────────────────────────────
cat > "$ASSETS_DIR/agoraiq-mobile.css" << 'CSS_EOF'
/* AgoraIQ shared mobile-responsive styles
   Loaded on every page via /assets/agoraiq-mobile.css
   Last update: auto-generated by deploy-mobile.sh */

:root{
  --aiq-safe-top:env(safe-area-inset-top,0px);
  --aiq-safe-bottom:env(safe-area-inset-bottom,0px);
}

/* Lock brand text to Syne universally — bulletproof against fallbacks */
.brand-text,.brand-text *,.footer-brand,.footer-brand *{
  font-family:'Syne','Albert Sans',system-ui,-apple-system,'Segoe UI',Roboto,sans-serif!important;
  font-weight:800!important;
  letter-spacing:-.02em;
}

/* Hamburger toggle button (injected by JS, hidden on desktop) */
.aiq-nav-toggle{
  display:none;
  background:transparent;
  border:1px solid var(--border,#1e2230);
  border-radius:8px;
  color:var(--text,#e4e7ef);
  width:40px;
  height:40px;
  align-items:center;
  justify-content:center;
  cursor:pointer;
  padding:0;
  flex-shrink:0;
  -webkit-tap-highlight-color:transparent;
}
.aiq-nav-toggle:active{background:var(--surface2,#161822)}
.aiq-nav-toggle svg{width:20px;height:20px;display:block}

/* ≤900px: collapse topbar nav into hamburger drawer */
@media(max-width:900px){
  .aiq-nav-toggle{display:inline-flex}
  .topbar{position:relative;padding-top:calc(16px + var(--aiq-safe-top))}
  .topbar > nav{
    display:none!important;
    position:absolute;
    top:100%;
    left:0;
    right:0;
    flex-direction:column!important;
    align-items:stretch!important;
    justify-content:flex-start!important;
    background:var(--surface,#0e1017);
    border-bottom:1px solid var(--border,#1e2230);
    box-shadow:0 8px 24px rgba(0,0,0,.4);
    padding:8px 0!important;
    gap:0!important;
    z-index:200;
    max-height:calc(100vh - 80px);
    overflow-y:auto;
    -webkit-overflow-scrolling:touch;
  }
  .topbar > nav.aiq-open{display:flex!important}
  .topbar > nav > a{
    padding:14px 24px!important;
    border-bottom:1px solid var(--border,#1e2230);
    font-size:14px;
    white-space:normal;
  }
  .topbar > nav > a:last-child{border-bottom:none}
}

/* ≤768px: tighten container padding */
@media(max-width:768px){
  .container{padding-left:16px!important;padding-right:16px!important}
}

/* ≤480px: small phone tightening for topbar + footer */
@media(max-width:480px){
  .topbar{padding:14px 16px!important;padding-top:calc(14px + var(--aiq-safe-top))!important}
  .brand-text{font-size:16px!important}
  .legal-footer{padding:28px 16px!important;padding-bottom:calc(28px + var(--aiq-safe-bottom))!important}
}

/* Touch devices: kill sticky hover lift */
@media(hover:none){
  .plan-card:hover,.card:hover,.signal-card:hover,.provider-card:hover{transform:none}
}

/* Prevent iOS input zoom */
@media(max-width:768px){
  input[type="text"],input[type="email"],input[type="password"],
  input[type="search"],input[type="number"],input[type="tel"],
  input[type="url"],textarea,select{font-size:16px!important}
}
CSS_EOF
echo "✓ Wrote $ASSETS_DIR/agoraiq-mobile.css"

# ─────────────────────────────────────────────────────────────────
# 2. Shared mobile JS — auto-injects hamburger into existing topbar
# ─────────────────────────────────────────────────────────────────
cat > "$ASSETS_DIR/agoraiq-mobile.js" << 'JS_EOF'
/* AgoraIQ shared mobile nav — auto-injects hamburger into .topbar nav
   Loaded on every page via /assets/agoraiq-mobile.js
   Idempotent: skips pages that already have their own toggle. */
(function(){
  "use strict";

  function init(){
    var topbar = document.querySelector(".topbar");
    if(!topbar) return;
    var nav = topbar.querySelector("nav");
    var brand = topbar.querySelector(".brand");
    if(!nav || !brand) return;

    // Skip if any hamburger already exists (e.g. pricing.html has its own)
    if(topbar.querySelector(".aiq-nav-toggle, .nav-toggle, [data-nav-toggle]")) return;

    // Build hamburger button
    var btn = document.createElement("button");
    btn.className = "aiq-nav-toggle";
    btn.type = "button";
    btn.setAttribute("aria-label","Menu");
    btn.setAttribute("aria-expanded","false");
    btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>';

    // Insert hamburger right before the nav
    nav.parentNode.insertBefore(btn, nav);

    // Toggle on click
    btn.addEventListener("click", function(e){
      e.stopPropagation();
      var open = nav.classList.toggle("aiq-open");
      btn.setAttribute("aria-expanded", open ? "true" : "false");
    });

    // Tap outside closes
    document.addEventListener("click", function(e){
      if(!nav.classList.contains("aiq-open")) return;
      if(nav.contains(e.target) || btn.contains(e.target)) return;
      nav.classList.remove("aiq-open");
      btn.setAttribute("aria-expanded","false");
    });

    // Tapping a nav link closes
    Array.prototype.forEach.call(nav.querySelectorAll("a"), function(a){
      a.addEventListener("click", function(){
        nav.classList.remove("aiq-open");
        btn.setAttribute("aria-expanded","false");
      });
    });

    // Resize back to desktop closes
    var mql = window.matchMedia("(min-width:901px)");
    var onChange = function(e){
      if(e.matches){
        nav.classList.remove("aiq-open");
        btn.setAttribute("aria-expanded","false");
      }
    };
    if(mql.addEventListener) mql.addEventListener("change", onChange);
    else if(mql.addListener) mql.addListener(onChange);
  }

  if(document.readyState === "loading"){
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
JS_EOF
echo "✓ Wrote $ASSETS_DIR/agoraiq-mobile.js"

# ─────────────────────────────────────────────────────────────────
# 3. Patch every HTML file
# ─────────────────────────────────────────────────────────────────
python3 << 'PY_EOF'
import os, re, glob

WEB = "/opt/agoraiq-signals/web"

# Optimized Google Fonts block (preconnect + Syne display=block + others swap)
NEW_FONT_BLOCK = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
    '<link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&display=block">\n'
    '<link href="https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&display=block" rel="stylesheet">\n'
    '<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Albert+Sans:wght@400;500;600;700;900&display=swap" rel="stylesheet">'
)

# Match any existing Google Fonts link tag (single combined link)
RE_OLD_FONTS = re.compile(
    r'<link\s+rel="preconnect"\s+href="https://fonts\.googleapis\.com"\s*/?>\s*'
    r'(?:<link\s+rel="preconnect"\s+href="https://fonts\.gstatic\.com"[^>]*>\s*)?'
    r'(?:<link[^>]+href="https://fonts\.googleapis\.com/css2[^"]*"[^>]*>\s*)+',
    re.IGNORECASE
)

VIEWPORT_META = '<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">'
THEME_META    = '<meta name="theme-color" content="#08090d">'

CSS_LINK = '<link rel="stylesheet" href="/assets/agoraiq-mobile.css">'
JS_TAG   = '<script src="/assets/agoraiq-mobile.js" defer></script>'

files = sorted(glob.glob(f"{WEB}/*.html"))
patched = skipped = 0

for f in files:
    name = os.path.basename(f)
    with open(f, "r", encoding="utf-8") as fh:
        html = fh.read()
    original = html

    # ── Patch 1: Google Fonts → optimized block ─────────────────
    # Only replace if the page actually loads Syne via Google Fonts
    if "fonts.googleapis.com" in html and "Syne" in html and "display=block" not in html:
        m = RE_OLD_FONTS.search(html)
        if m:
            html = html[:m.start()] + NEW_FONT_BLOCK + "\n" + html[m.end():]
        else:
            # Fallback: inject the block right after <head> if regex didn't match
            html = re.sub(r'(<head[^>]*>)', r'\1\n' + NEW_FONT_BLOCK, html, count=1)

    # ── Patch 2: Viewport meta (mandatory for mobile) ───────────
    if 'name="viewport"' not in html:
        html = re.sub(r'(<head[^>]*>)', r'\1\n' + VIEWPORT_META, html, count=1)

    # ── Patch 3: Theme color meta (status bar tint on mobile) ───
    if 'name="theme-color"' not in html:
        html = re.sub(r'(<head[^>]*>)', r'\1\n' + THEME_META, html, count=1)

    # ── Patch 4: Shared mobile CSS link ─────────────────────────
    if "/assets/agoraiq-mobile.css" not in html:
        if "</head>" in html:
            html = html.replace("</head>", CSS_LINK + "\n</head>", 1)

    # ── Patch 5: Shared mobile JS script ────────────────────────
    if "/assets/agoraiq-mobile.js" not in html:
        if "</body>" in html:
            html = html.replace("</body>", JS_TAG + "\n</body>", 1)

    if html != original:
        with open(f, "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"  ✓ patched: {name}")
        patched += 1
    else:
        print(f"  · skipped: {name} (already up to date)")
        skipped += 1

print(f"\n  Patched: {patched}   Skipped: {skipped}   Total: {len(files)}")
PY_EOF

# ─────────────────────────────────────────────────────────────────
# 4. Verify
# ─────────────────────────────────────────────────────────────────
echo
echo "▸ Verifying assets are reachable…"
ls -la "$ASSETS_DIR/"

echo
echo "▸ Done."
echo "  Backup:   $BACKUP_DIR"
echo "  Test on phone:   https://bot.agoraiq.net/pricing.html"
echo "                   https://bot.agoraiq.net/signals.html"
echo
echo "  If anything looks broken, restore with:"
echo "    cp $BACKUP_DIR/*.html $WEB_DIR/"
